import { Inter } from "next/font/google";
import "./globals.css";
import{GlobalContextProvider} from "./context/store"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Swapnil Salon App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`} suppressHydrationWarning={true} >
        <GlobalContextProvider>
        {children}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
