import { Inter } from "next/font/google";
import "./globals.css";
import{GlobalContextProvider} from "./context/store"
import Navbar from "@/components/Navbar";
import Footer from './../components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Swapnil Salon App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `} suppressHydrationWarning={true} >
        <GlobalContextProvider>
          <div className=" ">
            <div>
              <Navbar/>
            </div>
           {children}
          <Footer/>
          </div>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
