import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sahil Shahu",
  description: "Generated by create next app",
  icons:{
    icon:["/favicon?v=4"]
  }
};
<link rel="icon" href="/favicon.ico" sizes="any" />
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true} >{children}</body>
    </html>
  );
}
