
import { Inter } from "next/font/google";
import "./globals.css";
import "@/styles/flaticon/font/flaticon.css"
import { GlobalContextProvider } from "./context/store";
import Navbar from "@/components/Navbar";
import Footer from './../components/Footer';
import Topbar from "@/components/Topbar";


const inter = Inter({ subsets: ["latin"] });

 export const metadata = {
  title: "RK Detailing Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-sans bg-slate-100`} suppressHydrationWarning={true}>
      <GlobalContextProvider>
        <div className="relative">
          <Topbar/>
          <div className="sticky top-0 ... z-50">
          <Navbar/>
          </div>
        
          {children}
          <Footer/>
        </div>
       </GlobalContextProvider>
      </body>
    </html>
  );
}
